kind: Service
apiVersion: v1
metadata:
  name: simple-gateway
spec:
  selector:
    app: simple-gateway
  ports:
    - protocol: TCP
      port: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-gateway
spec:
  selector:
    matchLabels:
      app: simple-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-gateway
    spec:
      serviceAccountName: simple-gateway
      containers:
        - name: simple-gateway
          image: rhardt/scgtest:0.0.11
          ports:
            - containerPort: 8080
