apiVersion: v1
kind: ServiceAccount
metadata:
    labels:
      app: simple-gateway
    name: simple-gateway
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: cm-reader
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["configmaps", "pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cm-reader-rb
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cm-reader
subjects:
  - kind: ServiceAccount
    name: simple-gateway
    namespace: default